### ISSUE TITLE
Ability to change the Congnito User pool post stack deployment

### ISSUE THREAD

**Issue by archtryingtocode** [awslabs/fhir-works-on-aws-deployment#614]
I have used FHIR works on AWS cloud formation template. Now would like to use another Cognito Userpool instead of the one created with the stack creation.

I have changed the user pool in API gateway - authorizer. 

I then try to generate the token and with the token run Patient update. This step gives error - Unauthorised. 

Is this because of the fact that its not possible to update APIGateway authorizer with a new Cognito USer Pool ?

Br

**Comment by nguyen102** [comment]
Hi @archtryingtocode,

We have not try switching the Cognito user pool post deployment. However, technically you should be able to do it. Note, you will need to generate a new id token using [init-auth.py](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/scripts/init-auth.py). Provide the script with your new `clientId` and `region`. Make sure that the user `workshopuser` has been created and that user is assigned to the `practitioner` group.

**Comment by archtryingtocode** [comment]
Hi Tim,

Thanks a lot for your response. Is there a detailed document which explains setting up FHIR works on AWS on local and then generate scripts to be deployed in AWS ?

It would be great if you can point me to the right document. I would then setup on Mac and then push via cloudformation/CDK to AWS. As I can see I would need to customize a lot of details.

Regards
Aman

**Comment by nguyen102** [comment]
HI @archtryingtocode,

We don't have specific documentation for generating scripts to be deployed to AWS. I can point you to the instructions we do have.

[This](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/DEVELOPMENT.md) is the documentation for pulling the code, making changes, and running it locally.

[This](https://github.com/awslabs/fhir-works-on-aws-deployment#accessing-fhir-works-on-aws) is the general deployment instruction.

To make updates to what is deployed to AWS you can edit [this file](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/serverless.yaml). You can learn  more about serverless [here](https://www.serverless.com/)

-Tim

**Comment by archtryingtocode** [comment]
Hi,

I have setup the project locally and have modified the Cognito user pool to accept mobile number as user and then confirm the user via OTP using Custom-Auth and Lambda triggers. I have also added user to Practitioner user group.

While testing with postman I always received 403- forbidden error. I tried looking into the error logs and this is what I can see. I have check the token passed via jwt.io<http://jwt.io> and it contains the basic details as mentioned:

Token :
```json
{
  "sub": "e097c100-29fc-40b9-b2d9-1f498192923f",
  "cognito:groups": [
    "practitioner"
  ],
  "iss": "https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_",
  "phone_number_verified": true,
  "cognito:username": “+91MobileNumber",
  "origin_jti": "fba7de06-02d0-4e18-b755-65e456728dff",
  "aud": "7fkcaos39hs8e4ofuli68420va",
  "token_use": "id",
  "auth_time": 1651447067,
  "name": "+91MobileNumber",
  "phone_number": "+91MobileNumber",
  "exp": 1651483655,
  "iat": 1651480055,
  "jti": "0605d39a-d73f-416b-a840-e8219a8ac76e"
}
```

Error Log from Cloudwatch:
```
2022-05-01T21:44:53.972Z 8b3d11dd-b033-4cc5-a4a6-dd684d270753 ERROR UnauthorizedError: Unauthorized
    at RBACHandler.isAllowed (/var/task/src/webpack:/Users/amanjha/Documents/GitHub/fhir-works-on-aws-deployment/node_modules/fhir-works-on-aws-authz-rbac/lib/RBACHandler.js:79:1)
    at RBACHandler.verifyAccessToken (/var/task/src/webpack:/Users/amanjha/Documents/GitHub/fhir-works-on-aws-deployment/node_modules/fhir-works-on-aws-authz-rbac/lib/RBACHandler.js:32:1)
    at /var/task/src/webpack:/Users/amanjha/Documents/GitHub/fhir-works-on-aws-deployment/node_modules/fhir-works-on-aws-routing/lib/app.js:89:1
    at Layer.handle [as handle_request] (/var/task/src/webpack:/Users/amanjha/Documents/GitHub/fhir-works-on-aws-deployment/node_modules/express/lib/router/layer.js:95:1)
    at trim_prefix (/var/task/src/webpack:/Users/amanjha/Documents/GitHub/fhir-works-on-aws-deployment/node_modules/express/lib/router/index.js:317:1)
    at /var/task/src/webpack:/Users/amanjha/Documents/GitHub/fhir-works-on-aws-deployment/node_modules/express/lib/router/index.js:284:1
    at Function.process_params (/var/task/src/webpack:/Users/amanjha/Documents/GitHub/fhir-works-on-aws-deployment/node_modules/express/lib/router/index.js:335:1)
    at next (/var/task/src/webpack:/Users/amanjha/Documents/GitHub/fhir-works-on-aws-deployment/node_modules/express/lib/router/index.js:275:1)
    at setContentTypeMiddleware (/var/task/src/webpack:/Users/amanjha/Documents/GitHub/fhir-works-on-aws-deployment/node_modules/fhir-works-on-aws-routing/lib/router/middlewares/setContentType.js:16:1)
    at Layer.handle [as handle_request] (/var/task/src/webpack:/Users/amanjha/Documents/GitHub/fhir-works-on-aws-deployment/node_modules/express/lib/router/layer.js:95:1) {
  isUnauthorizedError: true
}
```



I also checked in the code RBACHandler.js ( Method - verifyAccessToken)
```javascript
async verifyAccessToken(request) {
        var _a, _b;
        const decoded = (_a = jsonwebtoken_1.decode(request.accessToken, { json: true })) !== null && _a !== void 0 ? _a : {};
        const groups = (_b = decoded['cognito:groups']) !== null && _b !== void 0 ? _b : [];
        if (request.bulkDataAuth) {
            this.isBulkDataAccessAllowed(groups, request.bulkDataAuth);
            return decoded;
        }
        this.isAllowed(groups, request.operation, request.resourceType);
        return decoded;
    }
```

I am using post method to create a patient from the examples given. I must say here if I use out of the box solution provided then it works. When I am trying to change the cognito user pool it doesn’t work. I can see the token has cognate:groups and resourceType is also set to Patient. I cannot find request.resource type in postman logs.

The changes I have made to the Cognito user pool are listed below:

```yaml
Resources:
  # Creates a role that allows Cognito to send SNS messages
  SNSRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "cognito-idp.amazonaws.com<http://cognito-idp.amazonaws.com>"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "CognitoSNSPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "sns:publish"
                Resource: "*"
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref AWS::StackName
      AutoVerifiedAttributes:
        - phone_number
      MfaConfiguration: "ON"
      SmsConfiguration:
        ExternalId: !Sub ${AWS::StackName}-external
        SnsCallerArn: !GetAtt SNSRole.Arn
      Schema:
        - AttributeDataType: String
          Name: phone_number
          Required: true
        - AttributeDataType: String
          Name: cc_confirmed
        - AttributeDataType: String
          Name: tenantId
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      ClientName: !Sub '${AWS::StackName}-UserPool'
      UserPoolId: !Ref UserPool
      CallbackURLs:
        - !Ref CognitoOAuthDefaultRedirectURL
      DefaultRedirectURI: !Ref CognitoOAuthDefaultRedirectURL
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
      PreventUserExistenceErrors: ENABLED
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref UserPoolClient
      UserPoolId: !Ref UserPool
  PatientUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: This is a patient, who can see ones own data
      GroupName: patient
      Precedence: 0
      UserPoolId: !Ref UserPool
  PractitionerUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: This is a member of the hospital staff, who directly helps patients
      GroupName: practitioner
      Precedence: 0
      UserPoolId: !Ref UserPool
  NonPractitionerUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: This is a member of the hospital staff who needs access to non-medical record
      GroupName: non-practitioner
      Precedence: 1
      UserPoolId: !Ref UserPool
  AuditorUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Someone who needs read, v_read and search access on patients
      GroupName: auditor
      Precedence: 2
      UserPoolId: !Ref UserPool
```

Any help would be much appreciated.
